name: auto_release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            bin_name: natx86
          - target: aarch64-unknown-linux-musl
            bin_name: natarm64

    outputs:
      version: ${{ steps.vars.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      # 读取 Cargo.toml 版本号
      - name: Set outputs
        id: vars
        run: |
          version=$(grep '^version =' Cargo.toml | head -n 1 | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT

      # 安装 cross
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # cross 编译
      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      # 重命名二进制
      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/nat ${{ matrix.bin_name }}

      # 上传 artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin_name }}
          path: ${{ matrix.bin_name }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      # checkout 仓库，保证 gh release 不报 .git 错误
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 下载 build 生成的二进制
      - uses: actions/download-artifact@v4
        with:
          path: release_bins

      # 创建 GitHub Release
      - name: GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version="${{ needs.build.outputs.version }}"
          echo "Releasing version $version"

          # 直接创建 Release，不删除旧 release
          gh release create v${version} release_bins/**/nat* \
            -n "$version" -t "$version" --latest --notes "Release $version"
