jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - arm-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup target add ${{ matrix.target }}

      - name: Install cross compiler
        run: |
          sudo apt-get update
          case "${{ matrix.target }}" in
            aarch64-unknown-linux-gnu)
              sudo apt-get install -y gcc-aarch64-linux-gnu
              ;;
            armv7-unknown-linux-gnueabihf|arm-unknown-linux-gnueabihf)
              sudo apt-get install -y gcc-arm-linux-gnueabihf
              ;;
          esac

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nat-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/nat
